In [1]:
# import necessary libraries
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors

In [2]:
# read the data
path="../data/books_with_ratings.csv"

books_with_ratings=pd.read_csv(path)
books_with_ratings.head(30)

user        isbn  rating  userTotalRatingCount  bookTotalRatingCount  \
0   277427  002542730X      10                   497                   171   
1     3363  002542730X       0                   901                   171   
2    11676  002542730X       6                 13602                   171   
3    12538  002542730X      10                  1351                   171   
4    13552  002542730X       0                   709                   171   
5    16795  002542730X       0                  2948                   171   
6    24194  002542730X       0                   287                   171   
7    25981  002542730X       0                   740                   171   
8    26535  002542730X       0                   770                   171   
9    28204  002542730X       0                   688                   171   
10   30533  002542730X       0                   477                   171   
11   31826  002542730X       0                   607                   171   
12   41084  002542730X       7                   243                   171   
13   43246  002542730X       0                  1534                   171   
14   44728  002542730X       0                   319                   171   
15   51883  002542730X       0                  1246                   171   
16   52584  002542730X      10                  2512                   171   
17   55548  002542730X       0                   673                   171   
18   60244  002542730X       0                  2236                   171   
19   71712  002542730X       6                   306                   171   
20   77809  002542730X       0                   394                   171   
21   80538  002542730X       7                   258                   171   
22   81045  002542730X       0                   232                   171   
23   82407  002542730X       0                   236                   171   
24   82831  002542730X       0                   422                   171   
25   86243  002542730X       7                   552                   171   
26   88733  002542730X       0                  1158                   171   
27  110934  002542730X       6                   262                   171   
28  111947  002542730X       0                   457                   171   
29  112026  002542730X       0                   589                   171   

                                                title             author  
0   Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
1   Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
2   Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
3   Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
4   Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
5   Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
6   Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
7   Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
8   Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
9   Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
10  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
11  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
12  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
13  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
14  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
15  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
16  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
17  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
18  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
19  Politically Correct Bedtime Stories: Modern Ta...  James Finn Garner  
20  Politica

In [3]:
# Preparing data table for analysis
books_with_ratings_pivot = pd.pivot_table(data=books_with_ratings, index='title', columns='user', values='rating', fill_value=0)
print(books_with_ratings_pivot.values)
books_with_ratings_pivot

[[0 0 0 ... 0 0 0]
 [9 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


user                                                254     2276    2766    \
title                                                                        
16 Lighthouse Road                                       0       0       0   
1984                                                     9       0       0   
1st to Die: A Novel                                      0       0       0   
2010: Odyssey Two                                        0       0       0   
204 Rosewood Lane                                        0       0       0   
...                                                    ...     ...     ...   
You Belong To Me                                         0       0       0   
Zen and the Art of Motorcycle Maintenance: An I...       0       0       0   
Zoya                                                     0       0       0   
\O\" Is for Outlaw"                                      0       0       0   
stardust                                                 0       0       0   

user                                                2977    3363    3757    \
title                                                                        
16 Lighthouse Road                                       0       0       0   
1984                                                     0       0       0   
1st to Die: A Novel                                      0       0       0   
2010: Odyssey Two                                        0       0       0   
204 Rosewood Lane                                        0       0       0   
...                                                    ...     ...     ...   
You Belong To Me                                         0       0       0   
Zen and the Art of Motorcycle Maintenance: An I...       0       0       0   
Zoya                                                     0       0       0   
\O\" Is for Outlaw"                                      0       0       0   
stardust                                                 0       0       0   

user                                                4017    4385    6242    \
title                                                                        
16 Lighthouse Road                                       0       0       0   
1984                                                     0       0       0   
1st to Die: A Novel                                      0       0       0   
2010: Odyssey Two                                        0       0       0   
204 Rosewood Lane                                        0       0       0   
...                                                    ...     ...     ...   
You Belong To Me                                         0       0       0   
Zen and the Art of Motorcycle Maintenance: An I...       0       0       0   
Zoya                                                     0       0       0   
\O\" Is for Outlaw"                                      0       0       0   
stardust                                                 0       0       0   

user                                                6251    ...  274004  \
title                                                       ...           
16 Lighthouse Road                                       0  ...       0   
1984                                                     0  ...       0   
1st to Die: A Novel                                      0  ...       0   
2010: Odyssey Two                                        0  ...       0   
204 Rosewood Lane                                        0  ...       0   
...                                                    ...  ...     ...   
You Belong To Me                                         0  ...       0   
Zen and the Art of Motorcycle Maintenance: An I...       0  ...       0   
Zoya                                                     0  ...       0   
\O\" Is for Outlaw"                                      0  ...       0   
stardust                                               

In [4]:
# Convert to 2D sparse matrıx
books_with_ratings_matrix = csr_matrix(books_with_ratings_pivot.values)
print(books_with_ratings_matrix)

  (0, 81)	6
  (0, 289)	8
  (0, 367)	5
  (0, 412)	5
  (0, 479)	8
  (0, 675)	5
  (0, 706)	6
  (1, 0)	9
  (1, 37)	9
  (1, 42)	8
  (1, 59)	7
  (1, 138)	9
  (1, 159)	10
  (1, 173)	9
  (1, 190)	8
  (1, 223)	10
  (1, 224)	10
  (1, 249)	10
  (1, 281)	10
  (1, 394)	10
  (1, 481)	9
  (1, 513)	9
  (1, 560)	10
  (1, 610)	9
  (1, 701)	9
  :	:
  (1962, 237)	7
  (1962, 295)	8
  (1962, 308)	9
  (1962, 327)	10
  (1962, 372)	10
  (1962, 389)	9
  (1962, 450)	7
  (1962, 454)	9
  (1962, 489)	7
  (1962, 502)	10
  (1962, 511)	8
  (1962, 550)	10
  (1962, 598)	8
  (1962, 706)	10
  (1962, 720)	8
  (1962, 752)	10
  (1962, 839)	9
  (1962, 889)	8
  (1963, 26)	8
  (1963, 212)	9
  (1963, 294)	9
  (1963, 349)	8
  (1963, 441)	9
  (1963, 688)	5
  (1963, 740)	7


In [9]:
# Train Model
model_knn = NearestNeighbors(algorithm='brute', metric='cosine')
model_knn.fit(books_with_ratings_matrix)

NearestNeighbors(algorithm='brute', metric='cosine')

In [10]:
book="Harry Potter and the Goblet of Fire (Book 4)"
X = books_with_ratings_pivot[books_with_ratings_pivot.index == book]
X
X.to_numpy().reshape(1,-1)
distances, indices = model_knn.kneighbors(X, n_neighbors=8)
# print(distances,indices)
print(indices.flatten())
print(distances.flatten())

[624 626 623 625 627 628 552  56]
[3.33066907e-16 3.56737979e-01 4.36135246e-01 4.53747917e-01
 5.85874643e-01 6.50405902e-01 7.42142869e-01 7.79063512e-01]


In [11]:
# function to return recommended books - this will be tested
def get_recommends(book=""):

    X = books_with_ratings_pivot[books_with_ratings_pivot.index == book]
    X = X.to_numpy().reshape(1, -1)
    distances, indices = model_knn.kneighbors(X, n_neighbors=8)
    recommended_books = []
    for x in reversed(range(1, 6)):
        bookrecommended = [
            books_with_ratings_pivot.index[indices.flatten()[x]], distances.flatten()[x]]
        recommended_books.append(bookrecommended)
    recommended_books = [book, recommended_books]

    return recommended_books

books = get_recommends("Harry Potter and the Goblet of Fire (Book 4)")
books

['Harry Potter and the Goblet of Fire (Book 4)',
 [["Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))",
   0.6504059022229809],
  ["Harry Potter and the Sorcerer's Stone (Book 1)", 0.5858746426494368],
  ['Harry Potter and the Order of the Phoenix (Book 5)', 0.4537479174596224],
  ['Harry Potter and the Chamber of Secrets (Book 2)', 0.43613524587269237],
  ['Harry Potter and the Prisoner of Azkaban (Book 3)', 0.3567379793339225]]]

In [8]:
# test function
books = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
print(books)

def test_book_recommendation():
  test_pass = True
  recommends = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
  if recommends[0] != "Where the Heart Is (Oprah's Book Club (Paperback))":
    test_pass = False
  recommended_books = ["I'll Be Seeing You", 'The Weight of Water', 'The Surgeon', 'I Know This Much Is True']
  recommended_books_dist = [0.8, 0.77, 0.77, 0.77]
  for i in range(2): 
    if recommends[1][i][0] not in recommended_books:
      test_pass = False
    if abs(recommends[1][i][1] - recommended_books_dist[i]) >= 0.05:
      test_pass = False
  if test_pass:
    print("You passed the challenge! 🎉🎉🎉🎉🎉")
  else:
    print("You haven't passed yet. Keep trying!")

test_book_recommendation()

["Where the Heart Is (Oprah's Book Club (Paperback))", [['The Weight of Water', 0.7708583572697412], ['The Surgeon', 0.7699410973804288], ['I Know This Much Is True', 0.7677075092617776], ['The Lovely Bones: A Novel', 0.7234864549790632], ['Blue Diary', 0.7182874979226525]]]
You passed the challenge! 🎉🎉🎉🎉🎉
